name: unitree-rl
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pytorch==2.3.1
  - torchvision==0.18.1
  - torchaudio==2.3.1
  - pytorch-cuda=12.1
  - numpy<1.24
  - pip
  - pip:
      - cycler
      - kiwisolver
      - matplotlib
      - opencv-python
      - pyparsing
      - python-dateutil
      - scipy
      - tensorboard
      - pyyaml
      - h5py