# policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/g1/motion.pt"
# policy_path: "logs/g1_walking_test/exported/policies/policy_lstm_1.pt" ### walking
# policy_path: "logs/g1_standing/exported/policies/policy_lstm_1.pt" ### standing
# policy_path: "logs/g1_squatting/exported/policies/policy_lstm_1.pt" ### squat

policy_path: "logs/g1_1/exported/policies/policy_1.pt" ### g1_1

# policy_path: "{LEGGED_GYM_ROOT_DIR}/imitation_learning/policies/g1_cloned_policy.pt" ### imitation learning

# Change xml file within scene.xml
# xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/g1_description/scene.xml"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/g1_description/g1_29dof.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

# 12dof ########################################################################################################################
# kps: [100, 100, 100, 150, 40, 40, 100, 100, 100, 150, 40, 40]
# kds: [2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2]
# default_angles: [-0.1,  0.0,  0.0,  0.3, -0.2, 0.0, 
#                   -0.1,  0.0,  0.0,  0.3, -0.2, 0.0]

# ang_vel_scale: 0.25
# dof_pos_scale: 1.0
# dof_vel_scale: 0.05
# action_scale: 0.25
# cmd_scale: [2.0, 2.0, 0.25]
# num_actions: 12
# num_obs: 47
# cmd_init: [0.5, 0, 0]

# 29dof ########################################################################################################################
kps: [
  # Left Leg (hip_pitch, hip_roll, hip_yaw, knee, ankle_pitch, ankle_roll)
  60.0, 80.0, 40.0, 120.0, 40.0, 40.0, 
  # Right Leg (hip_pitch, hip_roll, hip_yaw, knee, ankle_pitch, ankle_roll)
  60.0, 80.0, 40.0, 120.0, 40.0, 40.0,
  # Waist (yaw, roll, pitch) ← CORRECTED ORDER!
  45.0, 45.0, 45.0,                    
  # Left Arm (shoulder_pitch, shoulder_roll, shoulder_yaw, elbow, wrist_roll, wrist_pitch, wrist_yaw)
  14.0, 14.0, 14.0, 14.0, 14.0, 4.5, 4.5, 
  # Right Arm (shoulder_pitch, shoulder_roll, shoulder_yaw, elbow, wrist_roll, wrist_pitch, wrist_yaw)
  14.0, 14.0, 14.0, 14.0, 14.0, 4.5, 4.5
]
kds: [
  # Left Leg
  3.0, 6.0, 2.5, 8.0, 2.5, 2.5,        
  # Right Leg
  3.0, 6.0, 2.5, 8.0, 2.5, 2.5,
  # Waist (yaw, roll, pitch) ← CORRECTED ORDER!
  3.5, 5.0, 5.0,                        
  # Left Arm
  1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.5,   
  # Right Arm
  1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.5
]
default_angles: [
  # Left Leg
  -0.15, 0.0, 0.0, 0.4, -0.15, 0.0,
  # Right Leg
  -0.15, 0.0, 0.0, 0.4, -0.15, 0.0,
  # Waist
   0.0, 0.0, 0.0,
  # Left Arm
   0.2, 0.2, 0.0, 1.0, 0.0, 0.0, 0.0,
  # Right Arm 
   0.2, -0.2, 0.0, 1.0, 0.0, 0.0, 0.0
]
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 29
num_obs: 98

cmd_init: [0.0, 0, 0]

